//	conf自体のロード中にグローバルなステートを変更したり参照したりは基本ダメ
//	単純なデータやツールで編集するデータはjsonで、手入力が必要なデータはconfで定義する。
//	loadconf()はテーブルを返す。

//	全ての設定データを読み込む。
//	map.jsonは全マップの登録情報やイベントデータなどを含む。非常に大きくなる可能性もあるが、数MBであればSwitchでも秒はかからない。

_sysdict <- loadconf( "sysdict.json");

//	cloneしたてのprojectはdata,resourceが無い！この状態はテンプレートをインストールするまで解決しない。
if( !getResource( "/data")/*||1*/){
	printf( "WARN : Empty project! /data, /resource not found.\n");
}else{
	foreach( i in ("dict","setting","type","player","job","cond","skill","item","weapon","armor","enemy","map","quest","store","gvar","point","macro")){
		this[i] <- loadconf( `/data/${i}.json`);
	}

	local r = this._resource <- {};
	foreach( i in ("renderset","bgm","chara_etc","event_pic","chara_vox","efx","enemy_pic","equip_vox","map_vox","obj_vox","snd","voice","map_asset","uimap","gamepad")){
		r[i] <- loadconf( `/resource/${i}.json`);
	}
}
